name: Algolia

on:
  issue_comment:
    types: [created,edited,deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup-algolia-cli
        uses: algolia/setup-algolia-cli@v1.1.0
        env:
            ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
            ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}