# This is a basic workflow to help you get started with Actions
name: related-issues

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get-related-issues:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    steps:
      - id: search
        name: Search based on issue title
        uses: brob/algolia-issue-search@v1.0
        with: 
          app_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          api_key: ${{ secrets.ALGOLIA_API_KEY }}
          index_name: ${{ github.event.repository.name }}
          issue_title: ${{ github.event.issue.title }}

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
            issue-number: ${{ github.event.issue.number }}
            comment-author: 'github-actions[bot]'
            body-includes: While you wait, here are related issues

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          # GITHUB_TOKEN or a repo scoped PAT.
          token: ${{ github.token }}
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## While you wait, here are related issues:
            ${{ steps.search.outputs.issues_list }}
          edit-mode: replace
          
      - name: Add Algolia Record
        id: ingest
        uses: chuckmeyer/add-algolia-record@v0

        with:
          app_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          api_key: ${{ secrets.ALGOLIA_API_KEY }}
          index_name: ${{ github.event.repository.name }}
          record: |
            {
              "title": "${{ github.event.issue.title }}", 
              "url": "${{ github.event.issue.html_url }}", 
              "labels": "${{ github.event.issue.labels }}",
              "objectID": "${{ github.event.issue.number }}"
            }
